/* Generado por scripts/generar-idioma.py desde traduccion/en.txt.
   No editar a mano: se sobrescribe. */
COZUMEL_EN_CARGADO({
  textos: {
 "Inicio": "Home",
 "Principal": "Main",
 "Colección": "Collection",
 "Personaliza": "Personalize",
 "Personaliza tu joya": "Personalize your jewelry",
 "Nuestra historia": "Our story",
 "País y moneda": "Country and currency",
 "Comprar": "Shop",
 "Abrir menú": "Open menu",
 "Menú": "Menu",
 "Cerrar menú": "Close menu",
 "Contacto": "Contact",
 "Un pedacito de lo que regalamos.": "A little piece of what we give.",
 "Un pedacito de lo que regalamos": "A little piece of what we give",
 "Enlaces del pie de página": "Footer links",
 "Aviso legal": "Legal notice",
 "Privacidad": "Privacy",
 "Términos y condiciones": "Terms and conditions",
 "Volver arriba": "Back to top",
 "Cerrar": "Close",
 "Pulsera Dos Almas": "Dos Almas Bracelet",
 "Pulsera Mi Cielo": "Mi Cielo Bracelet",
 "Brazalete Eterno": "Eterno Cuff",
 "Collar Esencia": "Esencia Necklace",
 "Collar Destino": "Destino Necklace",
 "Kit Pedacito de Nosotros": "Pedacito de Nosotros Kit",
 "Kit Mi Consentida": "Mi Consentida Kit",
 "Kit a tu gusto": "Build-your-own kit",
 "Collar Esencia + Pulsera Dos Almas": "Esencia Necklace + Dos Almas Bracelet",
 "Collar Destino + Pulsera Mi Cielo": "Destino Necklace + Mi Cielo Bracelet",
 "Un Pedacito <em>de ti</em>": "A Little Piece <em>of You</em>",
 "días": "days",
 "horas": "hours",
 "min": "min",
 "seg": "sec",
 "Unidades limitadas en el lanzamiento.": "Limited units at launch.",
 "Déjanos tu email y tendrás acceso antes que nadie.": "Leave your email and get access before anyone else.",
 "✦ Entre las primeras 100 compras sortearemos <strong>5 videollamadas privadas con Adri</strong> ✦": "✦ Among the first 100 orders we'll give away <strong>5 private video calls with Adri</strong> ✦",
 "Tu email": "Your email",
 "Quiero acceso anticipado": "I want early access",
 "Acepto que Cozumel guarde mi email para avisarme del lanzamiento. <a href=\"privacidad.html\">Privacidad</a>": "I agree that Cozumel may keep my email to let me know about the launch. <a href=\"privacidad.html\">Privacy</a>",
 "Escribe un email válido": "Enter a valid email",
 "Marca la casilla para poder avisarte": "Tick the box so we can let you know",
 "Guardando…": "Saving…",
 "¡Listo! Te escribiremos antes del lanzamiento con tu acceso anticipado.": "You're in! We'll write to you before the launch with your early access.",
 "No se ha podido guardar. Inténtalo de nuevo en un momento": "We couldn't save it. Please try again in a moment",
 "Cozumel Jewelry · Regala un pedacito de ti": "Cozumel Jewelry · Give a little piece of you",
 "Joyas para regalar algo más que un accesorio: una memoria, un momento, una historia": "Jewelry to give more than an accessory: a memory, a moment, a story",
 "Adriana llevando piezas de Cozumel Jewelry": "Adriana wearing Cozumel Jewelry pieces",
 "Descubrir la colección": "Discover the collection",
 "Nuestras piezas, <em>en la vida real</em>": "Our pieces, <em>in real life</em>",
 "Porque una joya empieza a contar su historia cuando deja el estudio.": "Because a piece of jewelry starts telling its story when it leaves the studio.",
 "Adri con una pieza de Cozumel Jewelry puesta": "Adri wearing a Cozumel Jewelry piece",
 "Adri con una pieza puesta": "Adri wearing a piece",
 "Un regalo de Cozumel Jewelry recién abierto": "A Cozumel Jewelry gift, just opened",
 "Un regalo, recién abierto": "A gift, just opened",
 "Un momento cotidiano con una pieza de Cozumel Jewelry": "An everyday moment with a Cozumel Jewelry piece",
 "Un momento cotidiano": "An everyday moment",
 "Dos amigas con una pieza de Cozumel Jewelry": "Two friends with a Cozumel Jewelry piece",
 "Dos amigas": "Two friends",
 "Madre e hija con una pieza de Cozumel Jewelry": "Mother and daughter with a Cozumel Jewelry piece",
 "Madre e hija": "Mother and daughter",
 "Una pareja con una pieza de Cozumel Jewelry": "A couple with a Cozumel Jewelry piece",
 "Una pareja": "A couple",
 "Descubre la colección →": "Discover the collection →",
 "Primera colección": "First collection",
 "Un Pedacito de Mí": "A Little Piece of Me",
 "Los pedacitos de esta edición son limitados. No porque queramos que corras, sino porque cada pieza se graba una por una, con un acabado de calidad, y eso no se puede apurar ni multiplicar": "The pieces in this edition are limited. Not because we want you to rush, but because each one is engraved one by one, with a quality finish, and that can't be hurried or multiplied",
 "Si hay un pedacito que quieres que sea tuyo, o de alguien a quien quieras dar un pedacito de ti, este es el momento de comprarlo": "If there's a piece you want to be yours, or for someone you want to give a little piece of you to, now is the time to get it",
 "Unidades limitadas · Sorteo de 5 videollamadas con Adri en las 100 primeras compras": "Limited units · 5 video calls with Adri raffled among the first 100 orders",
 "Regala un pedacito de ti": "Give a little piece of you",
 "Descubrir ahora": "Discover now",
 "Un Pedacito de Ti": "A Little Piece of You",
 "Primer lanzamiento · unidades limitadas": "First launch · limited units",
 "Las primeras 100 compras participan en el sorteo de 5 videollamadas privadas con Adri.": "The first 100 orders enter the raffle for 5 private video calls with Adri.",
 "Regala un pedacito de ti.": "Give a little piece of you.",
 "De Adri para ti": "From Adri, for you",
 "Sorteo de 5 videollamadas con Adri en las 100 primeras compras": "5 video calls with Adri raffled among the first 100 orders",
 "¿Hablamos?": "Let's talk?",
 "Si tu pregunta no aparece en el FAQ, escríbenos directamente y te contestamos personalmente": "If your question isn't in the FAQ, write to us directly and we'll answer you personally",
 "Ir al formulario de contacto →": "Go to the contact form →",
 "La colección · Cozumel Jewelry": "The collection · Cozumel Jewelry",
 "Cinco piezas, edición de lanzamiento. Unidades limitadas": "Five pieces, launch edition. Limited units",
 "La colección": "The collection",
 "Cinco piezas personalizables": "Five personalizable pieces",
 "Cinco piezas personalizables para regalar a quien más quieres": "Five personalizable pieces to gift to the ones you love most",
 "Joyas grabadas para regalar<br>a quien más quieres": "Engraved jewelry to gift<br>to the ones you love most",
 "Ver producto →": "View product →",
 "Ver pieza →": "View piece →",
 "Personalizar →": "Personalize →",
 "✦ Sorteo de <strong>5 videollamadas con Adri</strong> en las 100 primeras compras ✦": "✦ <strong>5 video calls with Adri</strong> raffled among the first 100 orders ✦",
 "✦ Tu compra entra en el <strong>sorteo de 5 videollamadas con Adri</strong>. Solo para las 100 primeras compras: aún estás a tiempo ✦": "✦ Your order enters the <strong>raffle for 5 video calls with Adri</strong>. Only for the first 100 orders: there is still time ✦",
 "Nuestros kits": "Our kits",
 "Arma tu kit": "Build your kit",
 "Caja de regalo de Cozumel abierta con un collar y una pulsera dorados, junto a la tarjeta y la caja con lazo": "Open Cozumel gift box with a gold necklace and bracelet, next to the card and the box with a bow",
 "Una pulsera y un colgante, elegidos y grabados por ti.": "A bracelet and a pendant, chosen and engraved by you.",
 "Crear mi kit →": "Create my kit →",
 "Precio pendiente": "Price to be confirmed",
 "imagen pendiente": "image coming soon",
 "Personalizar · Cozumel Jewelry": "Personalize · Cozumel Jewelry",
 "Edición de lanzamiento · unidades limitadas": "Launch edition · limited units",
 "Acabado": "Finish",
 "Bañado en oro": "Gold-plated",
 "Plateado": "Silver-tone",
 "Oro": "Gold",
 "oro": "gold",
 "plata": "silver",
 "Grabado (opcional)": "Engraving (optional)",
 "Plata": "Silver",
 "<span class=\"acabado-dot acabado-dot--oro\" aria-hidden=\"true\"></span>Bañado en oro": "<span class=\"acabado-dot acabado-dot--oro\" aria-hidden=\"true\"></span>Gold-plated",
 "<span class=\"acabado-dot acabado-dot--plata\" aria-hidden=\"true\"></span>Plateado": "<span class=\"acabado-dot acabado-dot--plata\" aria-hidden=\"true\"></span>Silver-tone",
 "<span class=\"acabado-dot acabado-dot--oro\" aria-hidden=\"true\"></span>Oro": "<span class=\"acabado-dot acabado-dot--oro\" aria-hidden=\"true\"></span>Gold",
 "<span class=\"acabado-dot acabado-dot--plata\" aria-hidden=\"true\"></span>Plata": "<span class=\"acabado-dot acabado-dot--plata\" aria-hidden=\"true\"></span>Silver",
 "Acabado del collar": "Necklace finish",
 "Acabado de la pulsera": "Bracelet finish",
 "Precio": "Price",
 "pendiente de confirmar": "to be confirmed",
 "Precio pendiente de confirmar": "Price to be confirmed",
 "Envío incluido": "Shipping included",
 "Foto ampliada": "Enlarged photo",
 "Ver las otras piezas": "See the other pieces",
 "Tu joya, tus palabras": "Your jewelry, your words",
 "Elige tu grabado": "Choose your engraving",
 "Grabado": "Engraving",
 "Grabado<span> (opcional)</span>": "Engraving<span> (optional)</span>",
 "(opcional)": "(optional)",
 "Sin grabado": "No engraving",
 "Esta pieza no lleva grabado": "This piece has no engraving",
 "Una frase, una fecha o unas coordenadas": "A phrase, a date or some coordinates",
 "Nombre": "Name",
 "Fecha": "Date",
 "Mensaje": "Message",
 "Ej. Adri": "E.g. Adri",
 "Ej. 14.02.2024": "E.g. 14.02.2024",
 "Ej. siempre contigo": "E.g. always with you",
 "Mes de nacimiento": "Birth month",
 "La cartita que va en la caja": "The little card that goes in the box",
 "Grabado de alta calidad, pieza a pieza": "High-quality engraving, piece by piece",
 "Cada pieza se personaliza con un grabado de máxima precisión y calidad, realizado para conseguir un acabado elegante, definido y duradero. Un detalle único pensado para conservar ese significado especial durante mucho tiempo.": "Each piece is personalized with a high-precision, high-quality engraving, made for an elegant, crisp and lasting finish. A unique detail designed to keep that special meaning for a long time.",
 "Materiales": "Materials",
 "<strong>Acero inoxidable con baño de oro:</strong> acero inoxidable de alta calidad con un delicado baño de oro, seleccionado para conseguir un acabado elegante y sofisticado.": "<strong>Gold-plated stainless steel:</strong> high-quality stainless steel with a delicate gold plating, chosen for an elegant, sophisticated finish.",
 "<strong>Acero inoxidable:</strong> acero inoxidable de alta calidad, resistente y duradero, con un acabado limpio y atemporal.": "<strong>Stainless steel:</strong> high-quality stainless steel, strong and durable, with a clean, timeless finish.",
 "Envío incluido en el precio, con los impuestos de importación: no pagas nada más al recibirlo.": "Shipping is included in the price, along with import taxes: you pay nothing more when it arrives.",
 "Preparamos cada pieza con especial cuidado para que llegue lista para regalar o para convertirse en un recuerdo personal.": "We prepare each piece with special care so it arrives ready to give, or to become a personal keepsake.",
 "Cuidados": "Care",
 "Piezas bañadas en oro": "Gold-plated pieces",
 "Para conservar el brillo y el acabado dorado de tu joya durante más tiempo:": "To keep your jewelry's shine and gold finish for longer:",
 "Evita el contacto directo con perfumes, cremas, aceites y otros cosméticos.": "Avoid direct contact with perfumes, creams, oils and other cosmetics.",
 "No la expongas durante largos periodos al agua, al cloro o al agua de mar.": "Don't expose it to water, chlorine or seawater for long periods.",
 "Quítatela antes de ducharte, bañarte o practicar deporte.": "Take it off before showering, swimming or exercising.",
 "Guárdala en un lugar seco y, preferiblemente, dentro de su estuche cuando no la estés utilizando.": "Store it in a dry place, ideally in its case, when you're not wearing it.",
 "Para limpiarla, utiliza suavemente un paño suave y seco. Evita productos abrasivos o químicos.": "To clean it, gently use a soft, dry cloth. Avoid abrasive or chemical products.",
 "El baño de oro es un acabado delicado que puede presentar desgaste natural con el uso y el paso del tiempo.": "Gold plating is a delicate finish that may show natural wear with use and over time.",
 "Piezas de acero inoxidable": "Stainless steel pieces",
 "El acero inoxidable es un material resistente y pensado para el uso diario. Para mantener su aspecto original durante más tiempo:": "Stainless steel is a durable material made for everyday wear. To keep it looking like new for longer:",
 "Evita el contacto prolongado con perfumes, cremas y productos químicos.": "Avoid prolonged contact with perfumes, creams and chemicals.",
 "Después de exponer la pieza al agua, sécala cuidadosamente con un paño suave.": "After the piece gets wet, dry it carefully with a soft cloth.",
 "Evita el contacto con cloro y productos de limpieza.": "Avoid contact with chlorine and cleaning products.",
 "Guárdala en un lugar seco cuando no la utilices.": "Store it in a dry place when you're not wearing it.",
 "Para recuperar su brillo, límpiala suavemente con un paño de microfibra.": "To bring back its shine, gently clean it with a microfiber cloth.",
 "Con estos sencillos cuidados podrás mantener tu joya limpia, brillante y bonita durante mucho más tiempo.": "With these simple steps your jewelry will stay clean, shiny and beautiful for much longer.",
 "Ya solo falta regalarlo": "All that's left is to give it",
 "Regálale un pedacito de ti": "Give them a little piece of you",
 "Añadir al carrito": "Add to cart",
 "Añadiendo a tu carrito…": "Adding to your cart…",
 "Añadida": "Added",
 "No se pudo continuar, pulsa de nuevo": "Something went wrong, please tap again",
 "Grabado de<br>alta calidad": "High-quality<br>engraving",
 "Pieza<br>única": "One-of-a-kind<br>piece",
 "Creado para<br>regalar": "Made to<br>be given",
 "Un cielo que solo tú conoces": "A sky only you know",
 "Una placa pequeña en la muñeca para guardar el sitio exacto donde pasó: unas coordenadas, una fecha que importa, la frase que se les quedó de un viaje": "A small plate on the wrist to keep the exact place where it happened: some coordinates, a date that matters, the phrase that stuck with you from a trip",
 "Lo bueno de grabar un lugar es que solo funciona para ustedes. Cualquiera que la vea leerá unos números sueltos; ella va a ver la casa donde creció, la playa de cada verano, el sitio donde todo empezó. Un código privado que se lleva puesto": "The beauty of engraving a place is that it only works for the two of you. Anyone else will just see a few numbers; she'll see the house she grew up in, the beach of every summer, the place where it all began. A private code you can wear",
 "Acero inoxidable de alta calidad, en acabado dorado (baño de oro) o plata": "High-quality stainless steel, in a gold (gold-plated) or silver finish",
 "Cadena fina con placa, cierre ajustable": "Fine chain with plate, adjustable clasp",
 "Grabado de alta calidad: frase, fecha o coordenadas": "High-quality engraving: phrase, date or coordinates",
 "Un sitio que solo ustedes saben leer": "A place only you two can read",
 "Dos círculos, uno para cada una": "Two circles, one for each of you",
 "Dos círculos enlazados que no se sueltan ni se confunden el uno con el otro. Es la pieza que eliges cuando lo que quieres decir no necesita explicarse, porque ya se nota": "Two linked circles that never let go and never blur into one another. It's the piece you choose when what you want to say doesn't need explaining, because it already shows",
 "No lleva grabado y no le hace falta. Un aro sujeta al otro sin apretarlo, como una madre y una hija, dos hermanas o dos amigas de toda la vida. Ella lo va a entender en cuanto la vea, sin que tengas que decir nada": "It has no engraving and doesn't need one. One ring holds the other without squeezing it, like a mother and daughter, two sisters or two lifelong friends. She'll understand the moment she sees it, without you having to say a word",
 "Cadena fina, cierre ajustable": "Fine chain, adjustable clasp",
 "Dos círculos entrelazados como símbolo de unión": "Two interlocking circles as a symbol of union",
 "Lo que no se dice, pero se lleva puesto": "What goes unsaid, but is worn",
 "Un lugar, una fecha, unas palabras": "A place, a date, a few words",
 "Un brazalete rígido, ancho y limpio, del tipo que se pone una vez y ya no se quita. Grabado con lo que tú decidas: una fecha, un nombre, una frase corta que no necesite contexto": "A rigid, wide, clean cuff, the kind you put on once and never take off. Engraved with whatever you choose: a date, a name, a short phrase that needs no context",
 "Es la pieza más rotunda de la colección: se ve desde lejos y se nota al abrazar. Si buscas un regalo que no pase desapercibido, que le pregunten por él y ella tenga algo que contar, es este": "It's the boldest piece in the collection: you see it from afar and feel it in a hug. If you're looking for a gift that won't go unnoticed, one people ask her about so she has a story to tell, this is it",
 "Cuff ajustable, diseño minimalista": "Adjustable cuff, minimalist design",
 "Se ve desde lejos y se recuerda de cerca": "Seen from afar, remembered up close",
 "Doble cadena con placa grabable": "Double chain with engravable plate",
 "Dos cadenas que caen juntas: una fina, casi invisible, y otra con una placa esperando lo que tengas que decirle. Su nombre. El día en que nació. Eso que nunca le dices en voz alta": "Two chains that fall together: one fine, almost invisible, and another with a plate waiting for what you have to tell her. Her name. The day she was born. That thing you never tell her out loud",
 "Hay cosas que no salen bien dichas en voz alta, pero caben enteras en unas letras grabadas. Ella lo va a llevar puesto un martes cualquiera, sin ocasión, y lo va a tocar sin darse cuenta mientras piensa en otra cosa. Ahí es donde vive un buen regalo: en los días normales": "Some things don't come out right when said out loud, but they fit perfectly in a few engraved letters. She'll wear it on any old Tuesday, for no occasion, and touch it without noticing while she thinks about something else. That's where a good gift lives: in ordinary days",
 "Doble cadena: fina + placa grabable": "Double chain: fine + engravable plate",
 "Grabado de alta calidad, personalizable con lo que quieras: un nombre, una fecha o una frase": "High-quality engraving, personalized with whatever you want: a name, a date or a phrase",
 "Para que lleve puesto un pedacito de ti": "So she can wear a little piece of you",
 "Su mes, su piedra": "Her month, her stone",
 "Cada mes tiene su piedra y su flor. Eliges el de ella y el collar deja de ser un collar cualquiera: es el suyo, con el color exacto del mes en que nació": "Every month has its stone and its flower. You choose hers, and the necklace stops being just any necklace: it's hers, in the exact color of the month she was born",
 "Es el regalo fácil de acertar y difícil de olvidar: no hace falta saber su talla, ni su estilo, ni qué joyas tiene ya. Solo su cumpleaños. Y si te lo sabes, ya llevas media conversación ganada": "It's the gift that's easy to get right and hard to forget: you don't need to know her size, her style or what jewelry she already has. Just her birthday. And if you know that, you're already halfway there",
 "Cadena fina tipo eslabón, largo ajustable": "Fine link chain, adjustable length",
 "Piedra y flor según el mes de nacimiento": "Stone and flower based on birth month",
 "Su mes, su piedra, su collar": "Her month, her stone, her necklace",
 "Este es tu pedacito de cielo. Llévalo contigo": "This is your little piece of sky. Take it with you",
 "Ene": "Jan",
 "Feb": "Feb",
 "Mar": "Mar",
 "Abr": "Apr",
 "May": "May",
 "Jun": "Jun",
 "Jul": "Jul",
 "Ago": "Aug",
 "Sep": "Sep",
 "Oct": "Oct",
 "Nov": "Nov",
 "Dic": "Dec",
 "Enero": "January",
 "Febrero": "February",
 "Marzo": "March",
 "Abril": "April",
 "Mayo": "May",
 "Junio": "June",
 "Julio": "July",
 "Agosto": "August",
 "Septiembre": "September",
 "Octubre": "October",
 "Noviembre": "November",
 "Diciembre": "December",
 "Color granate": "Garnet color",
 "Color amatista": "Amethyst color",
 "Color aguamarina": "Aquamarine color",
 "Color diamante": "Diamond color",
 "Color esmeralda": "Emerald color",
 "Color perla": "Pearl color",
 "Color rubí": "Ruby color",
 "Color peridoto": "Peridot color",
 "Color zafiro": "Sapphire color",
 "Color ópalo": "Opal color",
 "Color topacio": "Topaz color",
 "Color turquesa": "Turquoise color",
 "Enero · Clavel y color granate": "January · Carnation and garnet color",
 "Febrero · Violeta y color amatista": "February · Violet and amethyst color",
 "Marzo · Narciso y color aguamarina": "March · Daffodil and aquamarine color",
 "Abril · Margarita y color diamante": "April · Daisy and diamond color",
 "Mayo · Espino y color esmeralda": "May · Hawthorn and emerald color",
 "Junio · Rosa y color perla": "June · Rose and pearl color",
 "Julio · Espuela de caballero y color rubí": "July · Larkspur and ruby color",
 "Agosto · Amapola y color peridoto": "August · Poppy and peridot color",
 "Septiembre · Aster y color zafiro": "September · Aster and sapphire color",
 "Octubre · Caléndula y color ópalo": "October · Marigold and opal color",
 "Noviembre · Crisantemo y color topacio": "November · Chrysanthemum and topaz color",
 "Diciembre · Nochebuena y color turquesa": "December · Poinsettia and turquoise color",
 "Naciste en el mes que empieza todo de nuevo, cuando el año todavía no sabe lo que va a ser y tú ya vas caminando con paso firme. El clavel florece aunque haga frío, aunque nadie lo esté mirando. El granate lleva tu color: profundo, callado, ardiendo por dentro": "You were born in the month when everything starts over, when the year doesn't yet know what it will be and you're already walking with a steady step. The carnation blooms even in the cold, even when no one is watching. The garnet carries your color: deep, quiet, burning inside",
 "Naciste entre el frío que se va y la primavera que todavía no llega, con la cabeza un poco en las nubes y el corazón puesto en quien lo merece. La violeta crece escondida, casi tímida, pero su color no se olvida jamás. La amatista es igual de discreta e igual de imposible de ignorar": "You were born between the cold that's leaving and the spring that hasn't arrived, with your head a little in the clouds and your heart set on whoever deserves it. The violet grows hidden, almost shy, but its color is never forgotten. The amethyst is just as discreet and just as impossible to ignore",
 "Naciste cuando el invierno todavía dudaba si irse, y tú llegaste sin miedo, de las primeras en atreverte. El narciso se atreve a florecer antes que las demás flores. El aguamarina tiene el color exacto de lo que ves cuando cierras los ojos y piensas en el mar": "You were born when winter was still unsure about leaving, and you arrived fearless, one of the first to dare. The daffodil dares to bloom before all the other flowers. The aquamarine has the exact color of what you see when you close your eyes and think of the sea",
 "Naciste con las ganas de empezar de nuevo cada vez que hace falta, sin miedo a caerte porque sabes que te vas a levantar. La margarita parece simple, pero crece en cualquier lado y siempre encuentra el sol. El diamante es lo más duro que hay, y aun así, lo que más brilla": "You were born ready to start over whenever you need to, unafraid of falling because you know you'll get back up. The daisy looks simple, but it grows anywhere and always finds the sun. The diamond is the hardest thing there is, and still, the one that shines the most",
 "Naciste con raíces profundas y un cariño que no se anda con medias tintas, de las que protegen a quien aman con uñas y dientes si hace falta. El espino tiene espinas, sí, pero cuando florece lo hace entero, sin guardarse nada. La esmeralda es el verde más intenso que existe, como tu forma de querer": "You were born with deep roots and a love that doesn't do things halfway, the kind who protects the people she loves tooth and nail if needed. The hawthorn has thorns, yes, but when it blooms it does so completely, holding nothing back. The emerald is the most intense green there is, like the way you love",
 "Naciste siendo dos cosas a la vez: curiosa e imposible de aburrir, dulce y con carácter. La rosa es la flor que todo el mundo reconoce, pero que nunca deja de sorprender. La perla se forma despacio, en silencio, hasta convertirse en algo que no tiene precio": "You were born two things at once: curious and impossible to bore, sweet and strong-willed. The rose is the flower everyone recognizes, yet it never stops surprising. The pearl forms slowly, in silence, until it becomes something priceless",
 "Naciste sintiendo todo el doble, aunque por fuera parezcas tranquila. La espuela de caballero crece alta y esbelta, imposible de no ver. El rubí es el rojo más intenso que existe, como lo que sientes cuando de verdad quieres a alguien": "You were born feeling everything twice as much, even if you look calm on the outside. The larkspur grows tall and slender, impossible to miss. The ruby is the most intense red there is, like what you feel when you truly love someone",
 "Naciste con luz propia, de las que entran a un lugar y todo cambia un poco. La amapola se abre entera al sol, sin guardarse nada. El peridoto tiene ese verde que solo se encuentra en las cosas que de verdad valen la pena": "You were born with your own light, the kind who walks into a room and changes it a little. The poppy opens fully to the sun, holding nothing back. The peridot has that green you only find in things truly worth it",
 "Naciste queriendo en los detalles pequeños, esos que nadie más nota pero que lo dicen todo. Aster significa estrella, y así quieres tú: en silencio, iluminando todo lo que tocas sin hacer ruido. El zafiro tiene ese azul profundo de las noches donde de verdad se ven las estrellas": "You were born loving in the small details, the ones nobody else notices but that say everything. Aster means star, and that's how you love: quietly, lighting up everything you touch without a sound. The sapphire has that deep blue of the nights when you can really see the stars",
 "Naciste buscando el equilibrio, la armonía, la belleza en las cosas simples. La caléndula se abre con el sol y se cierra con la noche, fiel a su propio ritmo. El ópalo cambia de color según la luz, como tú, que sabes adaptarte sin dejar de ser tú": "You were born seeking balance, harmony, beauty in simple things. The marigold opens with the sun and closes with the night, true to its own rhythm. The opal changes color with the light, like you, who know how to adapt without ever stopping being you",
 "Naciste sintiendo todo profundo, sin medias tintas, de las que aman con una intensidad que a veces asusta a los demás pero que a ti te sale natural. El crisantemo florece cuando casi todo lo demás ya se marchitó: una lealtad que resiste al tiempo. El topacio guarda ese calor dorado que tú también llevas por dentro": "You were born feeling everything deeply, never halfway, the kind who loves with an intensity that sometimes scares others but comes naturally to you. The chrysanthemum blooms when almost everything else has withered: a loyalty that stands the test of time. The topaz holds that golden warmth you carry inside too",
 "Naciste para iluminar cualquier lugar donde estés, de las que hacen que diciembre se sienta especial aunque haga frío afuera. La nochebuena florece en pleno invierno, justo cuando menos se espera. La turquesa tiene ese color de mar que tú también llevas contigo, vayas donde vayas": "You were born to light up wherever you are, the kind who makes December feel special even when it's cold outside. The poinsettia blooms in the middle of winter, just when you least expect it. The turquoise has that color of the sea that you carry with you too, wherever you go",
 "El Collar Esencia y la Pulsera Dos Almas juntos, que es como mejor funcionan: uno guarda lo que le escribes, la otra dice lo que no hace falta escribir": "The Esencia Necklace and the Dos Almas Bracelet together, which is how they work best: one keeps what you write to her, the other says what doesn't need writing",
 "Es el regalo de las fechas que importan: un cumpleaños, el Día de las Madres, una graduación, ese día que merece algo más que flores. Llega en una sola caja y se abre una sola vez, así que conviene que sea el día bueno": "It's the gift for the dates that matter: a birthday, Mother's Day, a graduation, that day that deserves more than flowers. It arrives in a single box and gets opened only once, so make it the right day",
 "Ella se queda con las dos piezas, o te quedas tú con una. Eso ya lo deciden ustedes. Lo que no cambia es que las dos salen del mismo sitio y cuentan la misma historia": "She keeps both pieces, or you keep one. That's up to the two of you. What doesn't change is that both come from the same place and tell the same story",
 "Collar Esencia: doble cadena con placa grabable": "Esencia Necklace: double chain with engravable plate",
 "Pulsera Dos Almas: dos círculos entrelazados, símbolo de unión": "Dos Almas Bracelet: two interlocking circles, a symbol of union",
 "Porque el amor también se lleva puesto": "Because love is something you wear too",
 "Hay una mujer que te lo dio todo sin pedir nada a cambio, o una que llegó y te cambió el rumbo. No importa si es tu mamá, tu hermana, tu novia o esa amiga que ya es familia: hay alguien que merece llevar puesto un pedacito de lo que sientes, aunque nunca se lo hayas dicho en voz alta": "There's a woman who gave you everything without asking for anything in return, or one who showed up and changed your course. It doesn't matter if she's your mom, your sister, your girlfriend or that friend who's already family: someone deserves to wear a little piece of what you feel, even if you've never said it out loud",
 "Collar Destino, con su piedra y su flor, elegidas por el mes en que llegó al mundo, porque ella también tiene su propio cielo. Pulsera Mi Cielo, grabada con lo que quieras decirle: una fecha, un lugar, una frase que solo ustedes entienden": "The Destino Necklace, with her stone and flower, chosen by the month she came into the world, because she has her own sky too. The Mi Cielo Bracelet, engraved with whatever you want to tell her: a date, a place, a phrase only the two of you understand",
 "Collar Destino: piedra y flor según el mes de nacimiento": "Destino Necklace: stone and flower based on birth month",
 "Pulsera Mi Cielo: placa grabable con fecha, lugar o frase": "Mi Cielo Bracelet: engravable plate with a date, place or phrase",
 "Arma tu kit · Cozumel Jewelry": "Build your kit · Cozumel Jewelry",
 "1 · Elige tu pulsera": "1 · Choose your bracelet",
 "Material de la pulsera": "Bracelet material",
 "2 · Elige tu colgante": "2 · Choose your pendant",
 "Material del colgante": "Pendant material",
 "Tu pulsera": "Your bracelet",
 "Sin elegir": "Not chosen",
 "Sin pieza elegida": "No piece chosen",
 "Tu colgante": "Your pendant",
 "Elige una pulsera y un colgante": "Choose a bracelet and a pendant",
 "Ahora elige tu colgante": "Now choose your pendant",
 "Ahora elige tu pulsera": "Now choose your bracelet",
 "Escribe el grabado de tu pulsera": "Write the engraving for your bracelet",
 "Escribe el grabado de tu colgante": "Write the engraving for your pendant",
 "No todos los pedacitos son iguales, y no todas las historias se cuentan con las mismas piezas. Aquí eliges tú: combina lo que quieras, para quien tú quieras, como tú lo sientas.": "Not every little piece is the same, and not every story is told with the same pieces. Here, you choose: combine whatever you want, for whoever you want, however you feel it.",
 "Un collar para tu mamá y una pulsera para ti. Dos piezas para tu mejor amiga. El set que tenga sentido para tu historia, no para la nuestra.": "A necklace for your mom and a bracelet for you. Two pieces for your best friend. The set that makes sense for your story, not ours.",
 "Elige las piezas que quieras combinar de toda la colección": "Choose the pieces you want to combine from the whole collection",
 "Cada una se personaliza por separado — su nombre, su fecha, su mensaje": "Each one is personalized separately — her name, her date, her message",
 "Envío en caja especial de regalo": "Shipped in a special gift box",
 "Porque no hay una sola forma de regalar un pedacito de ti.": "Because there's more than one way to give a little piece of you.",
 "Una pulsera y un colgante, a tu elección": "A bracelet and a pendant, your choice",
 "Las dos piezas que tú elijas, cada una con su acabado y su grabado, en la misma caja de regalo": "The two pieces you choose, each with its own finish and engraving, in the same gift box",
 "Caja de regalo abierta con un collar de placa y un brazalete plateados, grabados": "Open gift box with an engraved silver-tone plate necklace and cuff",
 "Caja de regalo abierta con un collar de flor y un brazalete dorados, grabado con una fecha": "Open gift box with a gold flower necklace and cuff, engraved with a date",
 "Caja de regalo abierta con un collar de flor y un brazalete plateados": "Open gift box with a silver-tone flower necklace and cuff",
 "Compra · Cozumel Jewelry": "Checkout · Cozumel Jewelry",
 "Último paso": "Last step",
 "Cómpratela": "Make it yours",
 "Pago seguro con tarjeta, a través de Stripe. Envío e impuestos incluidos": "Secure card payment through Stripe. Shipping and taxes included",
 "+ Añadir otra pieza": "+ Add another piece",
 "Todavía no has añadido ninguna pieza. Entra en <a href=\"productos.html\">la colección</a> y elige la tuya": "You haven't added any pieces yet. Visit <a href=\"productos.html\">the collection</a> and choose yours",
 "Tu nombre": "Your first name",
 "Apellidos": "Last name",
 "Tus apellidos": "Your last name",
 "tucorreo@email.com": "youremail@email.com",
 "Tu número": "Your number",
 "País": "Country",
 "Países": "Countries",
 "Elige el país de envío": "Choose the shipping country",
 "Dirección de envío": "Shipping address",
 "Calle, número, ciudad, código postal": "Street, number, city, ZIP/postal code",
 "RUT (obligatorio para la aduana de Chile)": "RUT (required by Chilean customs)",
 "DNI o RUC (obligatorio para la aduana de Perú)": "DNI or RUC (required by Peruvian customs)",
 "Tu DNI o RUC": "Your DNI or RUC",
 "CUIT o CUIL, 11 dígitos (obligatorio para la aduana de Argentina)": "CUIT or CUIL, 11 digits (required by Argentine customs)",
 "<strong>Envíos a Argentina:</strong> el precio incluye el envío, pero no el IVA de importación, que se paga al recibir el paquete. Para que la aduana lo libere tienes que estar dado de alta en el Domicilio Fiscal Electrónico (DFE) de ARCA. Si el paquete no se puede entregar (dirección incorrecta, ausencia…), se pierde y no hay devolución.": "<strong>Shipping to Argentina:</strong> the price includes shipping, but not import VAT, which is paid when the package arrives. For customs to release it, you must be registered with ARCA's Electronic Tax Address (Domicilio Fiscal Electrónico, DFE). If the package can't be delivered (wrong address, nobody home…), it is lost and there is no refund.",
 "Acepto que guarden estos datos para contactarme sobre esta reserva": "I agree that you may keep this information to contact me about this order",
 "Pagar y comprar": "Pay and buy",
 "Total": "Total",
 "Listo": "Done",
 "Hemos recibido tu pago de la edición de lanzamiento": "We've received your payment for the launch edition",
 "Te avisaremos por email en cuanto se envíe": "We'll email you as soon as it ships",
 "Confirmando tu pago": "Confirming your payment",
 "Esto tarda solo unos segundos": "This only takes a few seconds",
 "Pago cancelado": "Payment canceled",
 "No te hemos cobrado nada. Puedes intentarlo de nuevo cuando quieras": "You haven't been charged. You can try again whenever you like",
 "Volver a intentarlo": "Try again",
 "Tu carrito está vacío. Añade alguna pieza antes de comprar": "Your cart is empty. Add a piece before checking out",
 "Alguna pieza de tu carrito todavía no tiene precio, no se puede comprar": "A piece in your cart doesn't have a price yet, so it can't be purchased",
 "Ahora mismo no podemos procesar tu compra. Inténtalo de nuevo en unos minutos": "We can't process your order right now. Please try again in a few minutes",
 "Guardando tu pedido...": "Saving your order...",
 "No se pudo guardar tu pedido. Inténtalo de nuevo": "We couldn't save your order. Please try again",
 "Conectando con Stripe...": "Connecting to Stripe...",
 "No se pudo conectar con el pago. Inténtalo de nuevo": "We couldn't connect to the payment page. Please try again",
 "Tu pago está confirmándose, tarda más de lo normal. Revisa tu email en unos minutos": "Your payment is still being confirmed and it's taking longer than usual. Check your email in a few minutes",
 "Quiénes somos · Cozumel Jewelry": "About us · Cozumel Jewelry",
 "Quiénes somos": "About us",
 "Hay cosas que queremos llevar con nosotros": "Some things we want to carry with us",
 "No es una joya más. Es lo que no quieres soltar.": "It's not just another piece of jewelry. It's what you don't want to let go of.",
 "Adri dibujando diseños de joyas en un cuaderno frente al mar, junto al cartel de Cozumel": "Adri sketching jewelry designs in a notebook by the sea, next to the Cozumel sign",
 "Un nombre. Una fecha. Un lugar. O simplemente alguien.": "A name. A date. A place. Or simply someone.",
 "Escribimos eso en cada pieza — con un grabado de calidad, para que no se pierda.": "We write that on every piece — with a quality engraving, so it's never lost.",
 "Manos sosteniendo un collar de flor de Cozumel sobre la mesa de trabajo, con perlas y bocetos": "Hands holding a Cozumel flower necklace over the worktable, with pearls and sketches",
 "No todo se puede decir en voz alta": "Not everything can be said out loud",
 "Por eso lo grabamos. Un <strong>pedacito</strong> de ti, en algo que se lleva puesto todos los días.": "That's why we engrave it. A little <strong>piece</strong> of you, in something worn every day.",
 "Cuaderno con los bocetos del collar de flor junto a la pieza terminada en dorado": "Notebook with sketches of the flower necklace next to the finished gold piece",
 "Más que una joya": "More than jewelry",
 "Tú eliges qué contar": "You choose what to tell",
 "Tu nombre. Tu fecha. Tu mensaje. Personalizada con un grabado de calidad, solo para quien se la des.": "Your name. Your date. Your message. Personalized with a quality engraving, just for the person you give it to.",
 "No es una joya más. Es un pedacito de ti.": "It's not just another piece of jewelry. It's a little piece of you.",
 "Elige tu pieza →": "Choose your piece →",
 "Contacto · Cozumel Jewelry": "Contact · Cozumel Jewelry",
 "Si tienes una duda, quieres un grabado especial o simplemente quieres saber cuándo abrimos, escríbenos": "If you have a question, want a special engraving or just want to know when we open, write to us",
 "No rellenes este campo": "Don't fill in this field",
 "Enviar mensaje": "Send message",
 "Te contestamos al email que nos dejes": "We'll reply to the email you give us",
 "Respuesta": "Reply",
 "Te contestamos personalmente": "We answer you personally",
 "Escribe tu nombre": "Enter your name",
 "Escribe tu mensaje": "Write your message",
 "No se puede enviar ahora mismo. Escríbenos a cozumeljewel@gmail.com": "It can't be sent right now. Write to us at cozumeljewel@gmail.com",
 "Mensaje enviado. Te contestamos en cuanto lo leamos": "Message sent. We'll reply as soon as we read it",
 "No se pudo enviar. Inténtalo de nuevo o escríbenos a cozumeljewel@gmail.com": "It couldn't be sent. Try again or write to us at cozumeljewel@gmail.com",
 "Enviando…": "Sending…",
 "Página no encontrada · Cozumel Jewelry": "Page not found · Cozumel Jewelry",
 "Esta página no existe": "This page doesn't exist",
 "El enlace que has seguido no lleva a ningún sitio": "The link you followed doesn't lead anywhere",
 "Volver al inicio": "Back to home",
 "Preguntas frecuentes · Cozumel Jewelry": "FAQ · Cozumel Jewelry",
 "Ayuda": "Help",
 "Preguntas frecuentes": "Frequently asked questions",
 "Pedidos": "Orders",
 "¿Cómo puedo realizar un pedido?": "How do I place an order?",
 "Puedes realizar tu pedido directamente desde nuestra tienda online. Elige la joya que más te guste, selecciona las opciones disponibles y, si quieres personalizarla, añade tu grabado antes de completar la compra.": "You can order directly from our online store. Choose the piece you like best, select the available options and, if you want to personalize it, add your engraving before completing your purchase.",
 "¿Puedo modificar o cancelar mi pedido?": "Can I change or cancel my order?",
 "Si necesitas modificar o cancelar un pedido, ponte en contacto con nosotros lo antes posible. Intentaremos ayudarte siempre que el pedido todavía no haya entrado en proceso de preparación o personalización.": "If you need to change or cancel an order, contact us as soon as possible. We'll do our best to help as long as the order hasn't yet gone into preparation or personalization.",
 "¿Recibiré una confirmación de mi pedido?": "Will I get an order confirmation?",
 "Sí. Una vez completada la compra recibirás un email de confirmación con la información de tu pedido.": "Yes. Once your purchase is complete, you'll receive a confirmation email with your order details.",
 "Personalización": "Personalization",
 "¿Puedo personalizar mi joya?": "Can I personalize my jewelry?",
 "Sí. Algunas de nuestras piezas pueden personalizarse con nombres, fechas o mensajes especiales. Las opciones de personalización disponibles aparecen indicadas en cada producto.": "Yes. Some of our pieces can be personalized with names, dates or special messages. The available personalization options are shown on each product.",
 "¿Qué puedo grabar?": "What can I engrave?",
 "Puedes utilizar un nombre, una fecha, iniciales o un mensaje especial, siempre dentro de los límites de caracteres indicados para cada pieza.": "You can use a name, a date, initials or a special message, within the character limits shown for each piece.",
 "¿Cómo debo escribir el texto del grabado?": "How should I write the engraving text?",
 "Te recomendamos revisar cuidadosamente el texto antes de finalizar el pedido. La joya se personalizará siguiendo exactamente la información que hayas proporcionado.": "We recommend checking your text carefully before completing your order. The piece will be personalized exactly as you've written it.",
 "¿Puedo utilizar caracteres especiales o símbolos?": "Can I use special characters or symbols?",
 "Dependerá del tipo de personalización disponible en cada pieza. Si tienes una petición especial, escríbenos antes de realizar el pedido y te confirmaremos si es posible.": "It depends on the type of personalization available for each piece. If you have a special request, write to us before ordering and we'll confirm whether it's possible.",
 "¿Puedo cambiar el grabado después de realizar el pedido?": "Can I change the engraving after ordering?",
 "Las piezas personalizadas entran en proceso de preparación específicamente para cada pedido. Por ello, si necesitas modificar el grabado, contacta con nosotros cuanto antes.": "Personalized pieces go into preparation specifically for each order. So if you need to change the engraving, contact us as soon as possible.",
 "Envíos": "Shipping",
 "¿A dónde realizáis envíos?": "Where do you ship?",
 "A México, Estados Unidos, España y el resto de la Unión Europea, Chile, Perú, Colombia, Ecuador, Guatemala, El Salvador, Costa Rica y Argentina. Al hacer el pedido verás la lista de países disponibles. El envío, los impuestos y los aranceles ya están incluidos en el precio, salvo en Argentina, donde el IVA de importación se paga al recibir el paquete.": "To Mexico, the United States, Spain and the rest of the European Union, Chile, Peru, Colombia, Ecuador, Guatemala, El Salvador, Costa Rica and Argentina. When you order, you'll see the list of available countries. Shipping, taxes and duties are already included in the price, except in Argentina, where import VAT is paid when the package arrives.",
 "¿Cuánto tarda en llegar mi pedido?": "How long will my order take to arrive?",
 "Desde que sale del taller, en días laborables: Estados Unidos, de 6 a 12; España y Unión Europea, de 6 a 10; México, de 8 a 12; Perú, de 15 a 23; Chile y Colombia, de 19 a 21. Para Ecuador, Guatemala, El Salvador, Costa Rica y Argentina te confirmaremos el plazo por email después de tu pedido.": "From the moment it leaves the workshop, in business days: United States, 6 to 12; Spain and the European Union, 6 to 10; Mexico, 8 to 12; Peru, 15 to 23; Chile and Colombia, 19 to 21. For Ecuador, Guatemala, El Salvador, Costa Rica and Argentina, we'll confirm the delivery time by email after you order.",
 "Las piezas personalizadas pueden necesitar un tiempo adicional de preparación antes de salir.": "Personalized pieces may need some extra preparation time before they ship.",
 "¿Cómo puedo saber dónde está mi pedido?": "How can I track my order?",
 "Cuando tu pedido sea enviado, recibirás la información de seguimiento disponible para que puedas consultar su estado.": "When your order ships, you'll receive the available tracking information so you can check its status.",
 "¿Qué ocurre si no estoy en casa cuando llega el pedido?": "What happens if I'm not home when my order arrives?",
 "El transportista podrá realizar un nuevo intento de entrega o indicarte cómo recoger el paquete, dependiendo del servicio utilizado y del destino.": "The carrier may try to deliver again or tell you how to pick up the package, depending on the service and the destination.",
 "¿Qué hago si mi pedido llega dañado?": "What if my order arrives damaged?",
 "Si recibes un paquete aparentemente dañado, ponte en contacto con nosotros lo antes posible y envíanos fotografías del paquete y del producto para que podamos ayudarte a resolverlo.": "If you receive a package that looks damaged, contact us as soon as possible and send us photos of the package and the product so we can help you sort it out.",
 "Productos y materiales": "Products and materials",
 "¿De qué materiales están hechas las joyas?": "What materials is the jewelry made of?",
 "Cada producto puede tener unas características y materiales diferentes. Puedes consultar la información específica de cada pieza en su página de producto.": "Each product may have different features and materials. You'll find the specific information for each piece on its product page.",
 "¿Las joyas son resistentes al agua?": "Is the jewelry water-resistant?",
 "La resistencia al agua depende del material y del acabado de cada pieza. Consulta siempre las recomendaciones específicas de cada producto.": "Water resistance depends on each piece's material and finish. Always check the specific recommendations for each product.",
 "Como norma general, recomendamos evitar el contacto prolongado con agua, perfumes, cremas y productos químicos para conservar mejor la joya.": "As a general rule, we recommend avoiding prolonged contact with water, perfumes, creams and chemicals to keep your jewelry in better condition.",
 "¿Cómo debo cuidar mi joya?": "How should I care for my jewelry?",
 "Para mantener tu joya en las mejores condiciones:": "To keep your jewelry in the best condition:",
 "Evita el contacto con perfumes, cremas y productos químicos.": "Avoid contact with perfumes, creams and chemicals.",
 "Quítatela antes de ducharte, bañarte o hacer deporte.": "Take it off before showering, swimming or exercising.",
 "Guárdala en un lugar seco cuando no la estés utilizando.": "Store it in a dry place when you're not wearing it.",
 "Evita golpes y roces innecesarios.": "Avoid unnecessary knocks and rubbing.",
 "Límpiala suavemente cuando sea necesario.": "Clean it gently when needed.",
 "Un buen cuidado ayudará a mantener su aspecto durante más tiempo.": "Good care will help it keep its look for longer.",
 "Regalos": "Gifts",
 "¿Puedo enviar una joya directamente a otra persona?": "Can I send a piece directly to someone else?",
 "Sí. Puedes indicar una dirección de entrega diferente a la tuya durante el proceso de compra, siempre que el sistema de compra lo permita.": "Yes. You can enter a delivery address different from yours during checkout, as long as the checkout allows it.",
 "¿Puedo añadir un mensaje para la persona que recibe el regalo?": "Can I add a message for the person receiving the gift?",
 "Si esta opción está disponible durante el proceso de compra, podrás añadir tu mensaje personalizado.": "If this option is available during checkout, you'll be able to add your personal message.",
 "¿Qué pasa si completo la colección?": "What happens if I complete the collection?",
 "Si compras las cinco piezas de la colección, sueltas o dentro de un kit y aunque sea en varios pedidos, Adri te grabará un vídeo personal. Te lo enviaremos por email. Además, las 100 primeras compras entran en el sorteo de 5 videollamadas con Adri. <a href=\"terminos.html#lanzamiento\">Ver condiciones</a>.": "If you buy all five pieces in the collection, individually or in a kit, even across several orders, Adri will record a personal video for you. We'll send it to you by email. Plus, the first 100 orders enter the raffle for 5 video calls with Adri. <a href=\"terminos.html#lanzamiento\">See conditions</a>.",
 "¿Las joyas vienen preparadas para regalar?": "Does the jewelry come ready to give as a gift?",
 "Nuestros pedidos están preparados con especial cuidado para que la experiencia de recibir una joya Cozumel sea especial.": "Our orders are prepared with special care so that receiving a Cozumel piece feels special.",
 "Consulta la información del producto o del proceso de compra para conocer las opciones de packaging disponibles.": "Check the product or checkout information to see the available packaging options.",
 "Devoluciones": "Returns",
 "¿Puedo devolver mi pedido?": "Can I return my order?",
 "Cada pieza se fabrica y se graba a medida para ti, así que no funcionamos como una tienda de stock: no aceptamos devoluciones por cambio de opinión.": "Each piece is made and engraved to order for you, so we don't work like a store with stock: we don't accept returns for a change of mind.",
 "Aun así, queremos que quedes contento. Si algo no te convence (el tamaño, el acabado…), escríbenos dentro de los 15 días siguientes a la entrega y buscamos una solución contigo, caso por caso. No te vamos a pedir que nos envíes la pieza de vuelta.": "Even so, we want you to be happy. If something doesn't feel right (the size, the finish…), write to us within 15 days of delivery and we'll find a solution with you, case by case. We won't ask you to send the piece back.",
 "Puedes consultar el detalle en nuestros <a href=\"terminos.html\">términos y condiciones</a>.": "You can read the details in our <a href=\"terminos.html\">terms and conditions</a>.",
 "¿Puedo devolver una joya personalizada?": "Can I return a personalized piece?",
 "Al llevar tu grabado, una pieza personalizada no se puede volver a vender ni reutilizar, así que no admite devolución por cambio de opinión.": "Because it carries your engraving, a personalized piece can't be resold or reused, so it can't be returned for a change of mind.",
 "Si hay un problema real con la pieza, sí: escríbenos y lo resolvemos. Y si prefieres cancelar antes de que empiece la fabricación, puedes hacerlo sin coste.": "If there's a real problem with the piece, yes: write to us and we'll fix it. And if you'd rather cancel before production starts, you can do so at no cost.",
 "¿Qué hago si recibo un producto incorrecto o defectuoso?": "What if I receive the wrong or a defective product?",
 "Si la pieza llega con un defecto de fabricación o dañada, escríbenos dentro de los 15 días siguientes a recibirla, indicando tu número de pedido y adjuntando fotos. Conserva el embalaje original.": "If the piece arrives with a manufacturing defect or damaged, write to us within 15 days of receiving it, with your order number and photos attached. Keep the original packaging.",
 "En ese caso te reembolsamos el importe.": "In that case we'll refund the amount.",
 "¿Cómo puedo contactar con Cozumel?": "How can I contact Cozumel?",
 "Puedes contactar con nosotros a través de los canales de contacto disponibles en nuestra web. Estaremos encantados de ayudarte con cualquier duda sobre productos, personalización, pedidos o envíos.": "You can reach us through the contact channels on our website. We'll be happy to help with any question about products, personalization, orders or shipping.",
 "Tengo una duda que no aparece aquí, ¿qué hago?": "My question isn't here, what should I do?",
 "Escríbenos. Si tu pregunta no aparece en este FAQ, estaremos encantados de ayudarte directamente.": "Write to us. If your question isn't in this FAQ, we'll be happy to help you directly.",
 "Ir a contacto": "Go to contact",
 "Contactar": "Contact us",
 "Cookies · Cozumel Jewelry": "Cookies · Cozumel Jewelry",
 "Política de cookies": "Cookie policy",
 "Última actualización: 29 de agosto de 2026": "Last updated: August 29, 2026",
 "Qué usamos": "What we use",
 "Cozumel Jewelry usa únicamente almacenamiento técnico, necesario para que el sitio funcione — nada de publicidad ni de analítica de terceros:": "Cozumel Jewelry only uses technical storage needed for the site to work — no advertising and no third-party analytics:",
 "<strong>Un identificador de sesión anónimo</strong>, guardado en tu navegador (no es una cookie, es almacenamiento local), para medir de forma interna qué páginas se visitan antes de una reserva.": "<strong>An anonymous session identifier</strong>, saved in your browser (it's not a cookie, it's local storage), to measure internally which pages are visited before an order.",
 "<strong>Una sesión anónima de Supabase</strong>, guardada en tu navegador (almacenamiento local) al hacer un pedido. No es una cuenta ni guarda datos personales: solo sirve para que tu pedido sea tuyo y comprobar que se ha pagado.": "<strong>An anonymous Supabase session</strong>, saved in your browser (local storage) when you place an order. It isn't an account and stores no personal data: it only makes sure your order is yours and checks that it's been paid.",
 "Cuando pagas, sales de nuestro sitio hacia la página de pago de Stripe (un dominio distinto), que gestiona sus propias cookies bajo su propia política. Cozumel Jewelry no tiene acceso a esas cookies ni a tus datos de tarjeta.": "When you pay, you leave our site for Stripe's payment page (a different domain), which manages its own cookies under its own policy. Cozumel Jewelry has no access to those cookies or to your card details.",
 "Por qué no hay un banner de aceptar cookies": "Why there's no cookie consent banner",
 "La normativa española solo exige pedir tu consentimiento para cookies no esenciales (publicitarias o de analítica). Como las únicas que usamos son estrictamente necesarias para que el sitio y el inicio de sesión funcionen, no hace falta ese aviso.": "Spanish law only requires asking for your consent for non-essential cookies (advertising or analytics). Since the only ones we use are strictly necessary for the site and sign-in to work, that notice isn't needed.",
 "Cómo gestionar las cookies": "How to manage cookies",
 "Puedes borrar o bloquear las cookies desde la configuración de tu navegador en cualquier momento. Ten en cuenta que si bloqueas el almacenamiento de tu navegador, no vas a poder completar una compra.": "You can delete or block cookies in your browser settings at any time. Keep in mind that if you block your browser's storage, you won't be able to complete a purchase.",
 "Más información": "More information",
 "Para saber qué datos recogemos y para qué los usamos, consulta nuestra <a href=\"privacidad.html\">política de privacidad</a>.": "To find out what data we collect and what we use it for, see our <a href=\"privacidad.html\">privacy policy</a>.",
 "Aviso legal · Cozumel Jewelry": "Legal notice · Cozumel Jewelry",
 "Titular del sitio": "Site owner",
 "<strong>Eduardo Troncoso Domínguez</strong>, autónomo<br> NIF: 45140951R<br> Domicilio: Calle Manuel Pereira, nº 2, 32003 Ourense, Galicia, España<br> Correo electrónico: <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a><br> Teléfono: +34 604 09 48 68": "<strong>Eduardo Troncoso Domínguez</strong>, self-employed<br> Tax ID (NIF): 45140951R<br> Address: Calle Manuel Pereira, nº 2, 32003 Ourense, Galicia, Spain<br> Email: <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a><br> Phone: +34 604 09 48 68",
 "Cozumel Jewelry es el nombre comercial bajo el que Eduardo Troncoso Domínguez opera esta tienda online de joyería personalizada.": "Cozumel Jewelry is the trade name under which Eduardo Troncoso Domínguez runs this online store for personalized jewelry.",
 "Objeto": "Purpose",
 "Este sitio web permite conocer, personalizar y comprar las piezas de joyería de Cozumel Jewelry. El acceso y uso del sitio atribuye la condición de usuario y supone la aceptación de este aviso legal y de las condiciones de compra descritas en los <a href=\"terminos.html\">Términos y condiciones</a>.": "This website lets you discover, personalize and buy Cozumel Jewelry pieces. Accessing and using the site makes you a user and means you accept this legal notice and the purchase conditions described in the <a href=\"terminos.html\">Terms and conditions</a>.",
 "Propiedad intelectual": "Intellectual property",
 "Los textos, imágenes, logotipo y diseño de este sitio son propiedad de Eduardo Troncoso Domínguez o se usan con la autorización correspondiente. No está permitida su reproducción total o parcial sin permiso previo.": "The texts, images, logo and design of this site belong to Eduardo Troncoso Domínguez or are used with the corresponding authorization. Reproducing them in whole or in part without prior permission is not allowed.",
 "Enlaces a terceros": "Third-party links",
 "El proceso de pago se realiza a través de Stripe, un servicio de terceros con sus propias condiciones y políticas de privacidad, ajenas a Cozumel Jewelry.": "Payment is processed through Stripe, a third-party service with its own terms and privacy policies, independent of Cozumel Jewelry.",
 "Para cualquier consulta relacionada con este aviso legal, puedes escribir a <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>.": "For any question about this legal notice, you can write to <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>.",
 "Privacidad · Cozumel Jewelry": "Privacy · Cozumel Jewelry",
 "Política de privacidad": "Privacy policy",
 "Responsable del tratamiento": "Data controller",
 "<strong>Eduardo Troncoso Domínguez</strong>, autónomo · NIF 45140951R<br> Calle Manuel Pereira, nº 2, 32003 Ourense, Galicia, España<br> <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a> · +34 604 09 48 68": "<strong>Eduardo Troncoso Domínguez</strong>, self-employed · Tax ID (NIF) 45140951R<br> Calle Manuel Pereira, nº 2, 32003 Ourense, Galicia, Spain<br> <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a> · +34 604 09 48 68",
 "Como responsable, Cozumel Jewelry cumple con el Reglamento General de Protección de Datos (RGPD) y la normativa española aplicable.": "As data controller, Cozumel Jewelry complies with the General Data Protection Regulation (GDPR) and applicable Spanish law.",
 "Qué datos recogemos": "What data we collect",
 "Nombre, apellidos y dirección de envío, al hacer un pedido.": "First name, last name and shipping address, when you place an order.",
 "Correo electrónico y, si lo dejas, número de WhatsApp, para contactarte sobre tu pedido.": "Email and, if you provide it, WhatsApp number, to contact you about your order.",
 "El texto de personalización que eliges para el grabado.": "The personalization text you choose for the engraving.",
 "Los datos de pago los introducís directamente en Stripe: Cozumel Jewelry no los ve ni los almacena.": "You enter your payment details directly with Stripe: Cozumel Jewelry never sees or stores them.",
 "Tu correo electrónico, si te apuntas a la lista de espera del lanzamiento.": "Your email, if you join the launch waiting list.",
 "Para qué los usamos": "What we use it for",
 "Gestionar, fabricar y enviar tu pedido.": "To manage, make and ship your order.",
 "Comunicarnos contigo sobre el estado de tu pedido.": "To keep you updated on the status of your order.",
 "Mantener, mientras compras, una sesión anónima en tu navegador: no es una cuenta ni pide contraseña, solo sirve para que tu pedido sea tuyo.": "To keep an anonymous session in your browser while you shop: it isn't an account and doesn't ask for a password; it just makes sure your order is yours.",
 "Si te apuntas a la lista de espera, avisarte del lanzamiento para que puedas reservar tu pieza. Solo para eso: no te enviaremos publicidad por este motivo.": "If you join the waiting list, to let you know about the launch so you can reserve your piece. Only for that: we won't send you advertising because of it.",
 "Cumplir obligaciones legales, fiscales y contables.": "To meet legal, tax and accounting obligations.",
 "Con quién compartimos tus datos": "Who we share your data with",
 "<strong>EMANCO</strong> (nuestro fabricante, en China): recibe tu nombre, dirección de envío y el texto de personalización, lo necesario para fabricar y enviarte la pieza.": "<strong>EMANCO</strong> (our manufacturer, in China): receives your name, shipping address and personalization text, which is what's needed to make and ship your piece.",
 "<strong>Stripe</strong>: procesa el pago. Cozumel Jewelry no almacena datos de tarjetas.": "<strong>Stripe</strong>: processes the payment. Cozumel Jewelry doesn't store card details.",
 "<strong>Supabase</strong>: aloja la base de datos donde se guardan los pedidos.": "<strong>Supabase</strong>: hosts the database where orders are stored.",
 "No usamos herramientas de analítica de terceros (como Google Analytics o Meta Pixel) ni vendemos tus datos a nadie.": "We don't use third-party analytics tools (such as Google Analytics or Meta Pixel) and we don't sell your data to anyone.",
 "Cuánto tiempo los guardamos": "How long we keep it",
 "Mientras dure la relación derivada de tu pedido y, después, durante los plazos legales de conservación fiscal y contable que exige la normativa española (hasta 6 años según el Código de Comercio). El correo de la lista de espera se borra en cuanto pasa el lanzamiento, salvo que hagas un pedido.": "For as long as the relationship arising from your order lasts and, after that, for the legal tax and accounting retention periods required by Spanish law (up to 6 years under the Commercial Code). Waiting-list emails are deleted once the launch is over, unless you place an order.",
 "Tus derechos": "Your rights",
 "Puedes acceder, rectificar, suprimir, oponerte o pedir la limitación o portabilidad de tus datos escribiendo a <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>. Si no quedas satisfecho con la respuesta, puedes reclamar ante la <a href=\"https://www.aepd.es\" target=\"_blank\" rel=\"noopener\">Agencia Española de Protección de Datos (AEPD)</a>.": "You can access, correct, delete, object to, or request restriction or portability of your data by writing to <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>. If you're not satisfied with the answer, you can file a complaint with the <a href=\"https://www.aepd.es\" target=\"_blank\" rel=\"noopener\">Spanish Data Protection Agency (AEPD)</a>.",
 "Consulta el detalle en nuestra <a href=\"cookies.html\">política de cookies</a>.": "See the details in our <a href=\"cookies.html\">cookie policy</a>.",
 "Términos y condiciones · Cozumel Jewelry": "Terms and conditions · Cozumel Jewelry",
 "Quién vende": "Who sells",
 "Qué vendemos": "What we sell",
 "Piezas de joyería personalizada con grabado de alta calidad, bajo el nombre comercial Cozumel Jewelry. Los precios se indican en cada ficha de producto en euros; mientras aparezca como \"precio pendiente\", esa pieza todavía no está a la venta.": "Personalized jewelry pieces with high-quality engraving, under the trade name Cozumel Jewelry. Prices are shown in euros on each product page; while a piece shows \"price to be confirmed\", it isn't on sale yet.",
 "Cómo comprar": "How to buy",
 "Eliges la pieza, la personalizas con tu grabado y completas el pago con tarjeta a través de Stripe. Al pagar aceptas estos términos.": "You choose the piece, personalize it with your engraving and complete the card payment through Stripe. By paying, you accept these terms.",
 "Envío": "Shipping",
 "Las piezas se fabrican y se envían directamente desde nuestro taller de fabricación; no pasan por nuestras manos antes de llegarte. Enviamos a México, Estados Unidos, España y el resto de la Unión Europea, Chile, Perú, Colombia, Ecuador, Guatemala, El Salvador, Costa Rica y Argentina. Los países disponibles en cada momento son los que aparecen al hacer el pedido.": "Pieces are made and shipped directly from our workshop; they don't pass through our hands before reaching you. We ship to Mexico, the United States, Spain and the rest of the European Union, Chile, Peru, Colombia, Ecuador, Guatemala, El Salvador, Costa Rica and Argentina. The countries available at any time are the ones shown when you order.",
 "Plazo estimado de entrega desde que el pedido sale del taller, en días laborables: Estados Unidos, de 6 a 12; España y Unión Europea, de 6 a 10; México, de 8 a 12; Perú, de 15 a 23; Chile y Colombia, de 19 a 21. Para Ecuador, Guatemala, El Salvador, Costa Rica y Argentina, te confirmaremos el plazo por email después de tu pedido.": "Estimated delivery time from when the order leaves the workshop, in business days: United States, 6 to 12; Spain and the European Union, 6 to 10; Mexico, 8 to 12; Peru, 15 to 23; Chile and Colombia, 19 to 21. For Ecuador, Guatemala, El Salvador, Costa Rica and Argentina, we'll confirm the delivery time by email after you order.",
 "El envío está incluido en el precio, y también los impuestos y aranceles de importación: no tendrás que pagar nada más al recibir tu pedido.": "Shipping is included in the price, and so are import taxes and duties: you won't have to pay anything more when your order arrives.",
 "En Chile es obligatorio indicar tu RUT; en Perú, tu DNI o RUC, y en Argentina, tu CUIT o CUIL. Sin ellos la aduana no libera el paquete.": "In Chile you must provide your RUT; in Peru, your DNI or RUC; and in Argentina, your CUIT or CUIL. Without them, customs won't release the package.",
 "<strong>Envíos a Argentina.</strong> El precio incluye el envío, pero no el IVA de importación, que se paga al recibir el paquete. Para que la aduana lo libere hay que estar dado de alta en el Domicilio Fiscal Electrónico (DFE) de ARCA. Si el paquete no se puede entregar por una dirección incorrecta, por ausencia o por cualquier otro motivo ajeno a Cozumel Jewelry, se considera abandonado y no hay devolución ni reembolso.": "<strong>Shipping to Argentina.</strong> The price includes shipping, but not import VAT, which is paid when the package arrives. For customs to release it, you must be registered with ARCA's Electronic Tax Address (Domicilio Fiscal Electrónico, DFE). If the package can't be delivered because of a wrong address, because nobody is home or for any other reason beyond Cozumel Jewelry's control, it is considered abandoned and there is no return or refund.",
 "Pago": "Payment",
 "El pago se procesa de forma segura a través de Stripe. Cozumel Jewelry no almacena los datos de tu tarjeta.": "Payment is processed securely through Stripe. Cozumel Jewelry doesn't store your card details.",
 "Cancelaciones": "Cancellations",
 "Puedes cancelar tu pedido sin coste <strong>antes de que empiece la fabricación de tu pieza</strong>. Una vez iniciada la fabricación (al llevar tu grabado personalizado), ya no es posible cancelarlo. Para cancelar, escríbenos cuanto antes a <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>.": "You can cancel your order at no cost <strong>before production of your piece begins</strong>. Once production has started (since it carries your personalized engraving), it can no longer be canceled. To cancel, write to us as soon as possible at <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>.",
 "Como cada pieza se fabrica y se graba a medida para ti, no aceptamos devoluciones porque \"no te convenció\" del mismo modo que un producto de stock. Aun así, queremos que quedes contento con tu compra:": "Since each piece is made and engraved to order for you, we don't accept \"it wasn't for me\" returns the way a stock product would. Even so, we want you to be happy with your purchase:",
 "<strong>Si algo no te convence</strong> (el tamaño, el acabado, etc.), escríbenos dentro de los <strong>15 días</strong> siguientes a la entrega a <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>. Buscamos una solución caso por caso — no hay una respuesta única predefinida, y no vamos a pedirte que envíes la pieza de vuelta.": "<strong>If something doesn't feel right</strong> (the size, the finish, etc.), write to us within <strong>15 days</strong> of delivery at <a href=\"mailto:cozumeljewel@gmail.com\">cozumeljewel@gmail.com</a>. We'll find a solution case by case — there's no single predefined answer, and we won't ask you to send the piece back.",
 "<strong>Si la pieza llega con un defecto de fabricación</strong> o dañada, tienes hasta <strong>15 días desde que la recibes</strong> para avisarnos, con fotos como prueba y conservando el embalaje original. En ese caso, te reembolsamos el importe.": "<strong>If the piece arrives with a manufacturing defect</strong> or damaged, you have up to <strong>15 days from receiving it</strong> to let us know, with photos as proof and keeping the original packaging. In that case, we'll refund the amount.",
 "Escríbenos siempre indicando tu número de pedido.": "Always include your order number when you write to us.",
 "Ventajas del lanzamiento": "Launch perks",
 "<strong>Vídeo de Adri por completar la colección.</strong> Quien compre las cinco piezas de la colección <em>Un Pedacito de ti</em> (Pulsera Dos Almas, Pulsera Mi Cielo, Brazalete Eterno, Collar Esencia y Collar Destino) recibe un vídeo personal grabado por Adriana. Cuentan las piezas compradas sueltas o dentro de un kit, en uno o en varios pedidos, siempre con el mismo email. El vídeo se envía por email en los días siguientes a completar la colección. Si se devuelve alguna pieza, la colección deja de contar como completa.": "<strong>A video from Adri for completing the collection.</strong> Anyone who buys all five pieces in the <em>Un Pedacito de ti</em> collection (Dos Almas Bracelet, Mi Cielo Bracelet, Eterno Cuff, Esencia Necklace and Destino Necklace) gets a personal video recorded by Adriana. Pieces bought individually or in a kit count, in one or several orders, as long as they use the same email. The video is sent by email in the days after the collection is completed. If any piece is returned, the collection no longer counts as complete.",
 "<strong>Sorteo de 5 videollamadas con Adri.</strong> Participan las 100 primeras compras pagadas desde el lanzamiento (2 de octubre de 2026, a las 21:00 hora de México). Cada compra es una participación, tenga las piezas que tenga. Cozumel Jewelry elegirá 5 ganadores entre esas 100 compras y les avisará por el email con el que compraron; el día y la hora de cada videollamada se acuerdan con cada ganador. El premio es personal e intransferible y no se puede cambiar por dinero. Una compra cancelada o devuelta deja de participar. Para participar hay que ser mayor de edad.": "<strong>Raffle of 5 video calls with Adri.</strong> The first 100 paid orders from launch (October 2, 2026, at 9:00 PM Mexico time) take part. Each order is one entry, however many pieces it has. Cozumel Jewelry will choose 5 winners among those 100 orders and notify them at the email they used to buy; the day and time of each video call are arranged with each winner. The prize is personal, non-transferable and can't be exchanged for cash. A canceled or returned order no longer takes part. You must be of legal age to take part.",
 "Ley aplicable": "Governing law",
 "Estos términos se rigen por la legislación española. Si eres consumidor y hay algún desacuerdo, tienes derecho a acudir a los tribunales de tu domicilio.": "These terms are governed by Spanish law. If you're a consumer and there's a disagreement, you have the right to go to the courts where you live.",
 "Cambios en estos términos": "Changes to these terms",
 "Podemos actualizar este documento si cambian nuestras condiciones de venta; la fecha de \"última actualización\" arriba refleja la versión vigente.": "We may update this document if our terms of sale change; the \"last updated\" date above reflects the current version.",
 "Arabia Saudita": "Saudi Arabia",
 "Congo (Brazzaville)": "Congo (Brazzaville)",
 "Congo (Kinshasa)": "Congo (Kinshasa)",
 "Costa de Marfil": "Côte d'Ivoire",
 "Islas Malvinas": "Falkland Islands",
 "Malí": "Mali",
 "República Checa": "Czech Republic",
 "Timor Oriental": "Timor-Leste",
 "Collar": "Necklace",
 "Pulsera": "Bracelet",
 "El CUIT o CUIL tiene 11 dígitos": "The CUIT or CUIL has 11 digits",
 "EE. UU.": "USA"
},
  patrones: (T) => [
  [/^Ampliar foto: (.+), imagen (\d+) de (\d+)$/, (m, p, a, b) => `Enlarge photo: ${T(p)}, image ${a} of ${b}`],
  [/^Ver imagen (\d+) de (\d+)$/, 'View image $1 of $2'],
  [/^(.+), imagen (\d+) de (\d+)$/, (m, p, a, b) => `${T(p)}, image ${a} of ${b}`],
  [/^Ahorras (.+?) \((.+?) %\): por separado, las dos piezas cuestan (.+)$/, 'You save $1 ($2%): bought separately, the two pieces cost $3'],
  [/^Ahorras (.+)$/, 'You save $1'],
  [/^Quitar (.+) del carrito$/, (m, p) => `Remove ${T(p)} from cart`],
  [/^Son (\d+) caracteres\. Es posible que no quepan en la placa: si hace falta ajustarlo, te escribimos antes de grabar\.$/,
    "That's $1 characters. They may not fit on the plate: if it needs adjusting, we'll write to you before engraving."],
  [/^(.+) en (oro|plata) \+ (.+) en (oro|plata)(?: · Ahorras (.+) frente a comprarlas por separado \((.+)\))?$/,
    (m, p1, m1, p2, m2, ah, su) => `${T(p1)} in ${m1 === 'oro' ? 'gold' : 'silver'} + ${T(p2)} in ${m2 === 'oro' ? 'gold' : 'silver'}`
      + (ah ? ` · You save ${ah} compared with buying them separately (${su})` : '')],
  [/^Ir a pagar · (.+)$/, 'Checkout · $1'],
],
});
